Repository aviacommerce/avia, pull requests merged in 2018-10, with the labels that each got.

#223 [Admin] Fix taxon edit issue for blank image
  apps/admin_app/assets/package.json
  apps/admin_app/assets/yarn.lock
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
Labels: PR state: review and merge

#227 nginx installation with certbot
  Dockerfile
  apps/admin_app/assets/package-lock.json
  apps/admin_app/assets/package.json
  apps/admin_app/assets/yarn.lock
  apps/admin_app/config/prod.exs
  apps/snitch_core/config/config.exs
  apps/snitch_core/config/prod.exs
  package.json
  rel/commands/migrate.sh
  rel/config.exs
  rel/hooks/post_start/migrate.sh
  rel/hooks/pre_start/.keep
Labels: PR state: review and merge

#224 Restrict variation theme create without option type
  apps/admin_app/lib/admin_app_web/views/input_helpers.ex
  apps/snitch_core/lib/core/data/schema/variation_theme.ex
Labels: PR state: review and merge

#229 Using precompiled email template
  apps/snitch_core/lib/core/tools/mailer/email_templates/order_confirmation_email.html.eex
  apps/snitch_core/lib/core/tools/mailer/order_confirmation_email.ex
Labels: PR state: review and merge

#232 Updates templates for configuration forms.
  apps/admin_app/lib/admin_app_web/templates/payment_method/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/payment_method/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/permission/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/role/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/role/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/stock_location/_form.html.eex
Labels: PR state: review and merge

#235 Docker : added digest build with elm compilation
  Dockerfile
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
Labels: PR state: review and merge

#236 Fix variant create issue
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
Labels: PR state: review and merge

#241 Fixes Logo and favicon icons
  Dockerfile
  apps/admin_app/assets/static/favicon.ico
  apps/admin_app/assets/static/favicon.png
  apps/admin_app/assets/static/images/logo.png
  apps/admin_app/lib/admin_app_web/endpoint.ex
  apps/admin_app/lib/admin_app_web/templates/layout/app.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/header.html.eex
  apps/admin_app/lib/admin_app_web/templates/session/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/session/password_reset.html.eex
  config/deploy.example/dev-start.sh
Labels: PR state: review and merge

#244 Add Image url in API response for taxon
  apps/admin_app/lib/admin_app_web/templates/taxonomy/list.html.eex
  apps/snitch_core/lib/core/tools/helpers/taxonomy.ex
Labels: PR state: review and merge

#239 Updates pdf templates, download filename.
  apps/admin_app/config/config.exs
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/templates/order/invoice.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/order_total_summary.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/packing_slip.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  env/example.env
Labels: PR state: review and merge

#243 fixing order confirmation mail template
  apps/admin_app/assets/css/listing.scss
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/lib/core/tools/mailer/email_templates/order_confirmation_email.html.eex
  apps/snitch_core/lib/core/tools/mailer/order_confirmation_email.ex
  apps/snitch_core/mix.exs
Labels: DONT MERGE

#247 Auth fix for admin app
  apps/admin_app/lib/admin_app_web/controllers/session_controller.ex
  apps/snitch_core/lib/core/domain/account/account.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/users.ex
Labels: PR state: review and merge

#251 Adds minor changes to templates.
  README.md
  apps/admin_app/config/config.exs
  apps/admin_app/lib/admin_app_web/templates/layout/app.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/email.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/footer.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/header.html.eex
  apps/admin_app/lib/admin_app_web/templates/page/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/session/new.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/admin_app/lib/admin_app_web/views/page_view.ex
  apps/admin_app/lib/admin_app_web/views/session_view.ex
  apps/snitch_core/lib/core/tools/mailer/email_templates/order_confirmation_email.html.eex
  apps/snitch_core/lib/core/tools/mailer/email_templates/password_reset_email.html.eex
Labels: PR state: review and merge

#237 Product orderable state in API response
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
Labels: PR state: review and merge

#253 fixing order confirmation mail template
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/tools/mailer/email_templates/order_confirmation_email.html.eex
  apps/snitch_core/lib/core/tools/mailer/order_confirmation_email.ex
Labels: PR state: review and merge

#216 Store General Settings
  apps/admin_app/config/config.exs
  apps/admin_app/lib/admin_app_web/controllers/general_settings_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/general_settings/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/general_settings/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/general_settings/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/general_settings/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/views/general_settings_view.ex
  apps/admin_app/lib/admin_app_web/views/layout_view.ex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/snitch_api/config/prod.exs
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/application.ex
  apps/snitch_core/lib/core/data/model/general_configuration.ex
  apps/snitch_core/lib/core/data/schema/general_configuration.ex
  apps/snitch_core/lib/core/startup_code.ex
  apps/snitch_core/priv/repo/migrations/20180926103403_snitch_general_configurations.exs
  env/example.env
Labels: PR state: review and merge, tried and tested

#256 Add product sorting and filtering for product listing page.
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/product/index.js
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20181009090058_add_state_to_product.exs
  mix.lock
Labels: PR state: review and merge

#265 Sets default state to active for product listing
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/templates/option_type/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/product_brand/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/property/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/stock_location/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/user/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/user/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/variation_theme/form.html.eex
Labels: PR state: review and merge, enhancement

#255 Order listing
  apps/admin_app/assets/js/views/order/index.js
  apps/admin_app/lib/admin_app/order/order.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/templates/order/index.html.eex
  apps/snitch_api/config/prod.exs
  apps/snitch_core/lib/core/data/schema/order.ex
  apps/snitch_core/mix.exs
Labels: PR state: review and merge

#272 Updated docker config with multi-tenancy support
  Dockerfile
  apps/admin_app/lib/admin_app_web/controllers/general_settings_controller.ex
  apps/admin_app/lib/admin_app_web/views/layout_view.ex
  apps/snitch_core/lib/core/domain/account/account.ex
  apps/snitch_core/lib/core/startup_code.ex
  apps/snitch_core/lib/core/tools/multitenancy/repo.ex
  apps/snitch_core/test/support/data_case.ex
  config/deploy.example/prod-start.sh
Labels: Deployment, PR state: review and merge, tried and tested

#259 error handling for taxonomy deletion
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/snitch_api/lib/snitch_api/products_context/products_context.ex
  apps/snitch_api/lib/snitch_api_web/controllers/product_controller.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
Labels: PR state: review and merge

#270 Stock update
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/lib/core/data/schema/package_item.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
  apps/snitch_core/lib/core/domain/package.ex
  apps/snitch_core/test/domain/order/transitions_test.exs
  apps/snitch_core/test/support/factory/shipping.ex
Labels: PR state: review and merge

#273 Error handling for email delivery
  apps/snitch_core/lib/core/tools/mailer/order_confirmation_email.ex
Labels: PR state: review and merge, tried and tested

#269 Adds product property assoc feature
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/property_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/property_edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/property_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/property_index.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/property_new.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product_property.ex
  apps/snitch_core/lib/core/data/model/property.ex
  apps/snitch_core/lib/core/data/schema/product_property.ex
  apps/snitch_core/priv/repo/migrations/20181001103546_assoc_product_with_property.exs
  apps/snitch_core/test/data/model/product_property_test.exs
  apps/snitch_core/test/data/schema/product_property_test.exs
  apps/snitch_core/test/support/factory/factory.ex
Labels: PR state: review and merge, feature

#275 adding fixes for general_settings
  apps/admin_app/lib/admin_app_web/controllers/general_settings_controller.ex
  apps/admin_app/lib/admin_app_web/templates/general_settings/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/general_settings/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/product_brand/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/product_brand/new.html.eex
  apps/admin_app/lib/admin_app_web/views/general_settings_view.ex
  apps/snitch_core/config/config.exs
  apps/snitch_core/config/test.exs
  apps/snitch_core/lib/core/application.ex
  apps/snitch_core/lib/core/data/schema/general_configuration.ex
  apps/snitch_core/lib/core/startup_code.ex
  apps/snitch_core/lib/core/tools/mailer/order_confirmation_email.ex
  apps/snitch_core/priv/repo/migrations/20181015133937_alter_snitch_general_configurations.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/tools/mailer/order_confirmation_email_test.exs
Labels: PR state: review and merge

#278 Shipping rules
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/shipping_policy/index_edit.js
  apps/admin_app/lib/admin_app_web/controllers/shipping_policy_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/templates/shipping_policy/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/shipping_policy/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/shipping_policy/index.html.eex
  apps/admin_app/lib/admin_app_web/views/shipping_policy_view.ex
  apps/snitch_core/lib/core/data/model/shipping_category.ex
  apps/snitch_core/lib/core/data/model/shipping_rule.ex
  apps/snitch_core/lib/core/data/model/shipping_rule_identifier.ex
  apps/snitch_core/lib/core/data/schema/shipping_category.ex
  apps/snitch_core/lib/core/data/schema/shipping_rule.ex
  apps/snitch_core/lib/core/data/schema/shipping_rule_idenitifier.ex
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/lib/core/domain/package.ex
  apps/snitch_core/lib/core/domain/shipping_calculator.ex
  apps/snitch_core/priv/repo/migrations/20181016065101_shipping_rule_identifier_table.exs
  apps/snitch_core/priv/repo/migrations/20181016065112_shipping_rule_table.exs
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/shipping_rule.ex
  apps/snitch_core/test/data/model/shipping_category_test.exs
  apps/snitch_core/test/domain/order/transitions_test.exs
  apps/snitch_core/test/domain/package_test.exs
  apps/snitch_core/test/domain/shipping_calculator_test.exs
  apps/snitch_core/test/support/factory/shipping_category.ex
Labels: PR state: review and merge

#280 Stripe integration
  apps/snitch_api/lib/snitch_api/payment/hosted_payment.ex
  apps/snitch_api/lib/snitch_api_web/controllers/hosted_payment_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_api/lib/snitch_api_web/views/hosted_payment_view.ex
  mix.exs
  mix.lock
Labels: PR state: review and merge

#279 Adding sample data for the initial demo of the store.
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/data/schema/product_option_values.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/demo/.DS_Store
  apps/snitch_core/priv/repo/demo/demo.exs
  apps/snitch_core/priv/repo/demo/demo_data/options.csv
  apps/snitch_core/priv/repo/demo/demo_data/products.csv
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/analogwatch.jpeg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/blue_shirt.jpeg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/looms&weaves.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/neotia.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/polkadot.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/striped_tshirt.jpeg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/white_shirt.jpeg
  apps/snitch_core/priv/repo/demo/demo_data/stock_locations.csv
  apps/snitch_core/priv/repo/demo/demo_data/users.csv
  apps/snitch_core/priv/repo/demo/demo_data/variants.csv
  apps/snitch_core/priv/repo/demo/option_type.ex
  apps/snitch_core/priv/repo/demo/payment_methods.ex
  apps/snitch_core/priv/repo/demo/products.ex
  apps/snitch_core/priv/repo/demo/stock_locations.ex
  apps/snitch_core/priv/repo/demo/taxonomy.ex
  apps/snitch_core/priv/repo/demo/users.ex
  apps/snitch_core/priv/repo/demo/variation_themes.ex
  apps/snitch_core/priv/repo/seed/users.ex
  mix.lock
Labels: PR state: review and merge

#282 Admin dashboard feature
  apps/admin_app/assets/js/views/dashboard/index.js
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/lib/admin_app_web/controllers/dashboard_controller.ex
  apps/admin_app/lib/admin_app_web/helpers.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/dashboard/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/app.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/views/dashboard_view.ex
  apps/snitch_core/lib/core/data/model/order.ex
  apps/snitch_core/lib/core/data/model/payment/payment.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/tools/helpers/query_fragment.ex
  apps/snitch_core/priv/repo/migrations/20181024091825_add_postgres_money_aggregate_functions.exs
  apps/snitch_core/test/data/model/order_test.exs
  apps/snitch_core/test/data/model/payment/payment_test.exs
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/support/factory/factory.ex
Labels: PR state: review and merge

#285 background task for demo data
  apps/admin_app/config/config.exs
  apps/admin_app/lib/admin_app/application.ex
  apps/admin_app/lib/background_tasks/sample_data_task.ex
  apps/admin_app/lib/scheduler.ex
  apps/admin_app/mix.exs
  apps/snitch_core/lib/core/tools/multitenancy/repo.ex
  apps/snitch_core/priv/repo/demo/demo_data/products.csv
  apps/snitch_core/priv/repo/demo/products.ex
  mix.lock
Labels: PR state: review and merge

#295 Redirect to dashboard after login
  apps/admin_app/lib/admin_app_web/controllers/session_controller.ex
  apps/admin_app/lib/admin_app_web/views/dashboard_view.ex
Labels: PR state: review and merge
