Repository aviacommerce/avia, pull requests merged in 2018-09, with the labels that each got.

#158 Add Product Image Upload Feature
  apps/admin_app/assets/css/custom/custom.scss
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/js/product_file_upload.js
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/endpoint.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_api/mix.exs
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/image.ex
  apps/snitch_core/lib/core/data/schema/images/image.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20180709191108_create_images_table.exs
  apps/snitch_core/priv/repo/seed/product.ex
  mix.lock
Labels: PR state: review and merge, feature

#161 Product stock update and add to cart API
  apps/admin_app/assets/js/app.js
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/order/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_api/lib/snitch_api/order/order.ex
  apps/snitch_api/lib/snitch_api_web/controllers/line_item_controller.ex
  apps/snitch_api/lib/snitch_api_web/controllers/order_controller.ex
  apps/snitch_api/lib/snitch_api_web/views/line_item_view.ex
  apps/snitch_api/lib/snitch_api_web/views/order_view.ex
  apps/snitch_api/lib/snitch_api_web/views/product_option_value.ex
  apps/snitch_api/test/snitch_api_web/controllers/line_item_controller_test.exs
  apps/snitch_core/lib/core/data/model/line_item.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/stock/stock_item.ex
  apps/snitch_core/lib/core/data/model/stock/stock_location.ex
  apps/snitch_core/lib/core/data/model/wishlist_item.ex
  apps/snitch_core/lib/core/data/schema/line_item.ex
  apps/snitch_core/lib/core/data/schema/order.ex
  apps/snitch_core/lib/core/data/schema/package_item.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/data/schema/stock/stock_item.ex
  apps/snitch_core/lib/core/data/schema/wishlist_item.ex
  apps/snitch_core/lib/core/domain/shipment.ex
  apps/snitch_core/lib/core/tools/helpers/order.ex
  apps/snitch_core/lib/core/tools/helpers/stock.ex
  apps/snitch_core/priv/repo/migrations/20180826181820_assoc_product_with_stock_item.exs
  apps/snitch_core/priv/repo/migrations/20180828204145_add_product_assoc_to_line_item.exs
  apps/snitch_core/priv/repo/migrations/20180830184857_add_product_assoc_to_wishlist.exs
  apps/snitch_core/priv/repo/migrations/20180830201200_add_product_assoc_to_package_item.exs
  apps/snitch_core/priv/repo/migrations/20180831070126_add_shipping_category_assoc_to_product.exs
  apps/snitch_core/priv/repo/seed/orders.ex
  apps/snitch_core/priv/repo/seed/product.ex
  apps/snitch_core/priv/repo/seed/stocks.ex
  apps/snitch_core/test/data/model/line_item_test.exs
  apps/snitch_core/test/data/model/order_test.exs
  apps/snitch_core/test/data/model/package_item_test.exs
  apps/snitch_core/test/data/model/stock/stock_item_test.exs
  apps/snitch_core/test/data/model/stock/stock_location_test.exs
  apps/snitch_core/test/data/model/variant_test.exs
  apps/snitch_core/test/data/model/wishlist_test.exs
  apps/snitch_core/test/data/schema/line_item_test.exs
  apps/snitch_core/test/data/schema/order_test.exs
  apps/snitch_core/test/data/schema/package_item_test.exs
  apps/snitch_core/test/data/schema/package_test.exs
  apps/snitch_core/test/data/schema/variant_test.exs
  apps/snitch_core/test/data/schema/wishlist_test.exs
  apps/snitch_core/test/domain/calculator/default_calculator_test.exs
  apps/snitch_core/test/domain/shipment_engine_test.exs
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/domain/splitters/weight_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/factory/shipping.ex
  apps/snitch_core/test/support/factory/stock.ex
Labels: PR state: review and merge

#170 API Transition Address to Payment
  apps/snitch_api/lib/snitch_api/order/order.ex
  apps/snitch_api/lib/snitch_api_web/controllers/order_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_api/lib/snitch_api_web/views/order_view.ex
  apps/snitch_api/lib/snitch_api_web/views/payment_view.ex
  apps/snitch_core/lib/core/data/model/order.ex
  apps/snitch_core/lib/core/data/model/payment/hosted_payment.ex
  apps/snitch_core/lib/core/data/schema/order.ex
  apps/snitch_core/lib/core/data/schema/package.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
  apps/snitch_core/lib/core/domain/payment/payment.ex
  apps/snitch_core/mix.exs
Labels: PR state: review and merge, feature

#178 Add Transition Payment to Address
  apps/snitch_api/lib/snitch_api/order/order.ex
  apps/snitch_core/lib/core/data/model/order.ex
  apps/snitch_core/lib/core/data/model/package.ex
  apps/snitch_core/lib/core/data/model/payment/payment.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
Labels: PR state: review and merge, feature

#177 Taxonomy CRUD for Admin
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/js/create_taxon.js
  apps/admin_app/assets/js/edit_taxon.js
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/app.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax_category/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/list.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxon.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxonomy.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/admin_app/lib/admin_app_web/views/taxonomy_view.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
Labels: PR state: review and merge

#181 Add transition payment to rts
  apps/snitch_api/config/config.exs
  apps/snitch_api/lib/snitch_api/payment/hosted_payment.ex
  apps/snitch_api/lib/snitch_api_web/controllers/hosted_payment_controller.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  env/local.sh
Labels: PR state: review and merge, feature

#175 Product Create flow
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/js/create_taxon.js
  apps/admin_app/assets/js/edit_taxon.js
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxonomy.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/add_product.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/taxon_edit_form.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/admin_app/lib/admin_app_web/views/taxonomy_view.ex
  apps/admin_app/lib/admin_app_web/views/template_api/taxonomy_view.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/priv/repo/migrations/20180909172836_assoc_product_with_taxon.exs
  apps/snitch_core/priv/repo/migrations/20180910044805_assoc_taxon_with_variation_theme.exs
  apps/snitch_core/priv/repo/seed/orders.ex
  apps/snitch_core/priv/repo/seed/product.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/test/data/schema/product_test.exs
Labels: PR state: review and merge

#186 Order transition address to delivery
  apps/snitch_api/lib/snitch_api/order/order.ex
  apps/snitch_api/lib/snitch_api_web/controllers/order_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_api/lib/snitch_api_web/views/order_view.ex
  apps/snitch_api/lib/snitch_api_web/views/package_view.ex
  apps/snitch_api/lib/snitch_api_web/views/shipping_method_view.ex
  apps/snitch_api/test/snitch_api_web/controllers/line_item_controller_test.exs
  apps/snitch_api/test/snitch_api_web/controllers/order_controller_test.exs
  apps/snitch_core/lib/core/data/schema/shipping_category.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
Labels: PR state: review and merge, enhancement, feature

#187 Add API for COD payment
  apps/admin_app/lib/admin_app_web/controllers/payment_method_controller.ex
  apps/snitch_api/lib/snitch_api/order/order.ex
  apps/snitch_api/lib/snitch_api/payment/cod_payment.ex
  apps/snitch_api/lib/snitch_api/payment/hosted_payment.ex
  apps/snitch_api/lib/snitch_api_web/controllers/payment_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_core/lib/core/domain/payment/payment.ex
  mix.lock
Labels: PR state: review and merge

#189 AWS S3 for image upload
  .gitignore
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
  apps/snitch_core/mix.exs
  env/example.env
  env/local.sh
  mix.lock
Labels: PR state: review and merge

#190 Add guest line item API
  apps/snitch_api/lib/snitch_api_web/controllers/hosted_payment_controller.ex
  apps/snitch_api/lib/snitch_api_web/controllers/line_item_controller.ex
  apps/snitch_api/lib/snitch_api_web/controllers/order_controller.ex
  apps/snitch_api/lib/snitch_api_web/cors.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
Labels: PR state: review and merge

#193 Product delete
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/snitch_api/lib/snitch_api/products_context/products_context.ex
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/priv/repo/migrations/20180916062518_add_is_active_to_product.exs
Labels: PR state: review and merge

#204 Revamp Order Details Page Admin
  apps/admin_app/assets/js/app.js
  apps/admin_app/lib/admin_app/order/order.ex
  apps/admin_app/lib/admin_app/order/package.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/order/address_add.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/address_search.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/addresses.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/invoice.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/line_item.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/order_total_summary.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/packing_slip.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/show.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/order/order.ex
Labels: PR state: review and merge

#203 Image upload for taxon
  apps/admin_app/assets/js/views/taxonomy/taxonomy.js
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxonomy.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/taxon_edit_form.html.eex
  apps/admin_app/lib/admin_app_web/views/template_api/taxonomy_view.ex
  apps/snitch_core/lib/core/data/schema/images/product_brand_image.ex
  apps/snitch_core/lib/core/data/schema/images/taxon_image.ex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
  apps/snitch_core/priv/repo/migrations/20180919075640_snitch_taxon_images.exs
Labels: PR state: review and merge

#185 aws deployment config with docker setup
  Dockerfile
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/wkhtml/wkhtmltoimage
  apps/admin_app/assets/wkhtml/wkhtmltopdf
  apps/admin_app/config/config.exs
  apps/admin_app/config/prod.exs
  apps/admin_app/lib/admin_app_web.ex
  apps/admin_app/lib/admin_app_web/endpoint.ex
  apps/snitch_api/config/prod.exs
  apps/snitch_api/lib/snitch_api_web.ex
  apps/snitch_api/lib/snitch_api_web/endpoint.ex
  apps/snitch_core/config/prod.exs
  apps/snitch_core/lib/core/repo.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/tasks/release_tasks.ex
  config/.gitignore
  config/deploy.example/dev-start.sh
  config/deploy.example/docker-compose.yml
  config/deploy.example/shipit.sh
  env/local.env.remove_me
  mix.exs
  mix.lock
  rel/commands/migrate.sh
  rel/commands/seed.sh
  rel/config.exs
  rel/plugins/.gitignore
Labels: PR state: review and merge, feature, help wanted

#197 Taxonomy UI fixes
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/js/views/taxonomy/index.js
  apps/admin_app/assets/js/views/taxonomy/taxonomy.js
  apps/admin_app/config/config.exs
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/app.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/list.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxon.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxonomy.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/taxon_edit_form.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/admin_app/lib/admin_app_web/views/taxonomy_view.ex
  apps/admin_app/lib/admin_app_web/views/template_api/taxonomy_view.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
Labels: PR state: review and merge

#218 Shipping zone
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/zone/new.js
  apps/admin_app/lib/admin_app_web/controllers/zone_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/templates/zone/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/zone/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/zone/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/zone/new.html.eex
  apps/admin_app/lib/admin_app_web/views/zone_view.ex
  apps/snitch_core/lib/core/data/model/country.ex
  apps/snitch_core/lib/core/data/model/state.ex
  apps/snitch_core/lib/core/data/model/zone/country_zone.ex
  apps/snitch_core/lib/core/data/model/zone/state_zone.ex
  apps/snitch_core/lib/core/data/model/zone/zone.ex
  apps/snitch_core/lib/core/data/schema/zone/zone.ex
Labels: PR state: review and merge

#219 [Admin] Disable variation tab for child product.
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
Labels: PR state: review and merge
