Repository aviacommerce/avia, pull requests merged in 2018-05, with the labels that each got.

#55 Add selling_price to Variant, and tests
  apps/snitch_core/lib/core/data/model/line_item.ex
  apps/snitch_core/lib/core/data/schema/payment/payment.ex
  apps/snitch_core/lib/core/data/schema/schema.ex
  apps/snitch_core/lib/core/data/schema/variant.ex
  apps/snitch_core/lib/core/data/schema/zone/zone.ex
  apps/snitch_core/lib/core/tools/validations.ex
  apps/snitch_core/priv/repo/migrations/20180210100730_create_variant_table.exs
  apps/snitch_core/priv/repo/migrations/20180425115545_add_prices_to_variants.exs
  apps/snitch_core/priv/repo/seed/payment_methods.ex
  apps/snitch_core/test/data/model/line_item_test.exs
  apps/snitch_core/test/data/schema/payment/payment_test.exs
  apps/snitch_core/test/data/schema/variant_test.exs
  apps/snitch_core/test/data/schema/zone/zone_test.exs
  apps/snitch_core/test/support/factory/factory.ex
Labels: PR state: review and merge

#56 Add user, address, variant, order, lineitem seed data
  .formatter.exs
  apps/snitch_core/coveralls.json
  apps/snitch_core/lib/core/data/schema/address.ex
  apps/snitch_core/lib/core/data/schema/order.ex
  apps/snitch_core/priv/repo/migrations/20180501173309_order_slug_unique_index.exs
  apps/snitch_core/priv/repo/seed/orders.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/users.ex
Labels: enhancement

#58 Add TaxCategory model and schema
  .gitignore
  apps/snitch_core/lib/core/data/model/tax_category.ex
  apps/snitch_core/lib/core/data/schema/tax_category.ex
  apps/snitch_core/priv/repo/migrations/20180501173446_add_tax_category_table.exs
  apps/snitch_core/test/data/model/tax_category_test.exs
  apps/snitch_core/test/data/schema/tax_category_test.exs
  apps/snitch_core/test/support/factory/factory.ex
Labels: enhancement

#62 Speed up country, state seeding and add stock seeds
  .gitignore
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/data/model/country.ex
  apps/snitch_core/lib/core/data/model/state.ex
  apps/snitch_core/lib/core/data/schema/state.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20180506163501_rename_abbr_to_code_in_states.exs
  apps/snitch_core/priv/repo/seed/country_state_seed.ex
  apps/snitch_core/priv/repo/seed/orders.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/stocks.ex
  apps/snitch_core/priv/repo/seed/users.ex
  apps/snitch_core/test/data/schema/state_test.exs
  apps/snitch_core/test/support/factory/address.ex
  mix.lock
Labels: enhancement

#65 Associate country and state with address
  apps/snitch_core/lib/core/data/schema/address.ex
  apps/snitch_core/priv/repo/migrations/20180510064204_address_belongs_to_state_and_country.exs
  apps/snitch_core/test/data/model/tax_category_test.exs
  apps/snitch_core/test/data/schema/address_test.exs
  apps/snitch_core/test/data/schema/country_test.exs
  apps/snitch_core/test/support/factory/address.ex
Labels: enhancement

#68 modify defaults helper
  apps/snitch_core/lib/core/tools/defaults.ex
  apps/snitch_core/test/tools/defaults_test.exs
Labels: enhancement

#59 Taxonomy
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxonomy.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
  apps/snitch_core/lib/core/tools/helpers/taxonomy.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20180502103957_add_taxonomy.exs
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/taxonomy_seed.ex
  apps/snitch_core/test/domain/taxonomy/taxonomy_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/factory/taxonomy.ex
  apps/snitch_core/test/tools/helpers/taxonomy_test.exs
  mix.lock
Labels: PR state: review and merge

#71 Finds the common zone of two addresses
  apps/snitch_core/lib/core/data/model/zone/country_zone.ex
  apps/snitch_core/lib/core/data/model/zone/state_zone.ex
  apps/snitch_core/lib/core/data/schema/zone/zone.ex
  apps/snitch_core/lib/core/domain/zone.ex
  apps/snitch_core/lib/core/tools/helpers/zone.ex
  apps/snitch_core/test/data/model/zone/country_zone_test.exs
  apps/snitch_core/test/data/model/zone/state_zone_test.exs
  apps/snitch_core/test/data/model/zone/zone_test.exs
  apps/snitch_core/test/data/schema/zone/country_zone_member_test.exs
  apps/snitch_core/test/data/schema/zone/state_zone_member_test.exs
  apps/snitch_core/test/support/zone_case.ex
Labels: enhancement

#75 Compute shipping methods for packages
  apps/snitch_core/config/test.exs
  apps/snitch_core/lib/core/data/model/shipping_method.ex
  apps/snitch_core/lib/core/data/model/stock/stock_location.ex
  apps/snitch_core/lib/core/data/model/variant.ex
  apps/snitch_core/lib/core/data/schema/shipping_category.ex
  apps/snitch_core/lib/core/data/schema/shipping_method.ex
  apps/snitch_core/lib/core/data/schema/variant.ex
  apps/snitch_core/lib/core/domain/shipment.ex
  apps/snitch_core/lib/core/domain/shipping_method.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20180514151312_create_shipping_category.exs
  apps/snitch_core/priv/repo/migrations/20180516071627_associate_shipping_category_and_shipping_methods.exs
  apps/snitch_core/priv/repo/migrations/20180516175044_remove_constraint_from_zone_shipping_method.exs
  apps/snitch_core/test/data/model/shipping_method_test.exs
  apps/snitch_core/test/data/schema/shipping_category_test.exs
  apps/snitch_core/test/data/schema/shipping_method_test.exs
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/domain/shipping_method_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/factory/shipping.ex
  apps/snitch_core/test/support/order_case.ex
  apps/snitch_core/test/support/shipment_case.ex
  apps/snitch_core/test/support/stock_case.ex
  apps/snitch_core/test/support/zone_case.ex
  mix.lock
Labels: enhancement

#79 Mock ShippingMethod cost estimation
  apps/snitch_core/lib/core/data/model/country.ex
  apps/snitch_core/lib/core/data/model/state.ex
  apps/snitch_core/lib/core/domain/shipment.ex
  apps/snitch_core/lib/core/domain/shipping_method.ex
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/support/shipment_case.ex
Labels: feature

#82 Add PR and git commit templates
  .git_commit_msg.txt
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: enhancement

#81 Add shipment engine
  apps/snitch_core/lib/core/domain/shipment_engine.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/test/domain/shipment_engine_test.exs
  apps/snitch_core/test/domain/splitters/weight_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/shipment_engine_case.ex
  mix.lock
Labels: PR state: review and merge, feature

#83 Taxonomy Api
  apps/api/.gitignore
  apps/api/README.md
  apps/api/config/config.exs
  apps/api/config/dev.exs
  apps/api/config/prod.exs
  apps/api/config/test.exs
  apps/api/lib/api.ex
  apps/api/lib/api/application.ex
  apps/api/lib/api_web.ex
  apps/api/lib/api_web/channels/user_socket.ex
  apps/api/lib/api_web/controllers/fallback_controller.ex
  apps/api/lib/api_web/controllers/taxonomy_controller.ex
  apps/api/lib/api_web/cors.ex
  apps/api/lib/api_web/endpoint.ex
  apps/api/lib/api_web/gettext.ex
  apps/api/lib/api_web/router.ex
  apps/api/lib/api_web/views/changeset_view.ex
  apps/api/lib/api_web/views/error_helpers.ex
  apps/api/lib/api_web/views/error_view.ex
  apps/api/lib/api_web/views/taxonomy_view.ex
  apps/api/mix.exs
  apps/api/priv/gettext/en/LC_MESSAGES/errors.po
  apps/api/priv/gettext/errors.pot
  apps/api/test/api_web/views/error_view_test.exs
  apps/api/test/support/channel_case.ex
  apps/api/test/support/conn_case.ex
  apps/api/test/test_helper.exs
  apps/snitch_core/lib/core/data/schema/taxanomy/taxonomy.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
  apps/snitch_core/lib/core/tools/helpers/taxonomy.ex
  apps/snitch_core/priv/repo/seed/taxonomy_seed.ex
  mix.lock
Labels: PR state: review and merge

#85 custom colors for theme added
  apps/admin_app/assets/css/app.css.scss
  apps/admin_app/assets/css/custom/_variables.scss
  apps/admin_app/assets/css/custom/custom.scss
Labels: PR state: review and merge
