Repository aviacommerce/avia, pull requests merged in 2018-12, with the labels that each got.

#336 No brand selected for new product.
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
Labels: PR state: review and merge, feature

#340 Updates dashboard to display only required states.
  apps/admin_app/lib/admin_app_web/templates/dashboard/index.html.eex
  apps/snitch_core/lib/core/data/model/order.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/test/data/model/order_test.exs
Labels: PR state: review and merge, feature

#342 Fix long URL issue after product is edited with long description
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
Labels: PR state: review and merge, bug

#345 Fixes missing taxon in params when error in changeset.
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/add_product.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
Labels: PR state: review and merge, bug

#351 Fix image display
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
Labels: PR state: review and merge

#353 Default zone corresponding to stocklocation
  apps/admin_app/lib/admin_app_web/controllers/stock_location_controller.ex
  apps/admin_app/lib/admin_app_web/templates/stock_location/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/stock_location/show.html.eex
  apps/snitch_api/lib/snitch_api_web/views/stock_location_view.ex
  apps/snitch_core/lib/core/data/schema/stock/stock_location.ex
  apps/snitch_core/lib/core/data/schema/zone/zone.ex
  apps/snitch_core/lib/core/tools/helpers/stock.ex
  apps/snitch_core/priv/repo/demo/demo_data/stock_locations.csv
  apps/snitch_core/priv/repo/demo/stock_locations.ex
  apps/snitch_core/priv/repo/migrations/20181210061831_remove_admin_name.exs
  apps/snitch_core/priv/repo/seed/stock_location.ex
  apps/snitch_core/priv/repo/seed/stocks.ex
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/domain/splitters/weight_test.exs
  apps/snitch_core/test/support/factory/stock.ex
Labels: PR state: review and merge

#344 Product save & publish feature
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/product/edit.js
  apps/admin_app/assets/js/views/product/new.js
  apps/admin_app/assets/js/views/product/publish_helper.js
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/snitch_core/lib/core/data/schema/product.ex
Labels: PR state: review and merge, feature

#355 Fixes dashboard datetime issue.
  apps/admin_app/lib/admin_app_web/controllers/dashboard_controller.ex
Labels: PR state: review and merge, bug

#346 Order sample data
  .formatter.exs
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/demo/demo.exs
  apps/snitch_core/priv/repo/demo/demo_data/products.csv
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/armor_costume.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/gauntlet.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/groot_costume.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/kids_boots.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/latex_mask.jpg
  apps/snitch_core/priv/repo/demo/demo_data/static/product_images/student_costume.jpg
  apps/snitch_core/priv/repo/demo/option_type.ex
  apps/snitch_core/priv/repo/demo/order.ex
  apps/snitch_core/priv/repo/demo/payment_methods.ex
  apps/snitch_core/priv/repo/demo/products.ex
  apps/snitch_core/priv/repo/demo/stock_locations.ex
  apps/snitch_core/priv/repo/demo/taxonomy.ex
  apps/snitch_core/priv/repo/demo/users.ex
  apps/snitch_core/priv/repo/demo/variation_themes.ex
  apps/snitch_core/priv/repo/seed/orders.ex
Labels: PR state: review and merge

#347 Modify Shipping Policies
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/shipping_policy/edit.js
  apps/admin_app/assets/js/views/shipping_policy/index.js
  apps/admin_app/lib/admin_app_web/controllers/shipping_policy_controller.ex
  apps/admin_app/lib/admin_app_web/templates/shipping_policy/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/shipping_policy/preferences.html.eex
  apps/admin_app/lib/admin_app_web/views/shipping_policy_view.ex
  apps/snitch_core/lib/core/data/model/shipping_rule_identifier.ex
  apps/snitch_core/lib/core/data/schema/shipping_rule.ex
  apps/snitch_core/lib/core/data/schema/shipping_rule_idenitifier.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/order_conditional_free.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/order_flat_rate.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/order_free.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/product_flat_rate.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/shipping_rule.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/shipping_rule_idenitifier.ex
  apps/snitch_core/lib/core/domain/shipping_calculator.ex
  apps/snitch_core/priv/repo/migrations/20181206121850_alter_shipping_rules.exs
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/shipping_rule.ex
  apps/snitch_core/test/data/model/shipping_category_test.exs
  apps/snitch_core/test/data/schema/shipping_rules/order_conditional_free_test.exs
  apps/snitch_core/test/data/schema/shipping_rules/order_flat_rate_test.exs
  apps/snitch_core/test/data/schema/shipping_rules/order_free_test.exs
  apps/snitch_core/test/data/schema/shipping_rules/product_flat_rate_test.exs
  apps/snitch_core/test/domain/order/transitions_test.exs
  apps/snitch_core/test/domain/shipping_calculator_test.exs
  apps/snitch_core/test/support/factory/shipping_category.ex
Labels: feature

#356 Fixes variation theme dialogue box behaviour.
  apps/admin_app/assets/js/views/product/edit.js
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
Labels: PR state: review and merge, bug

#358 Display payment method name in order details.
  apps/admin_app/lib/admin_app/order/order.ex
  apps/admin_app/lib/admin_app_web/templates/order/show.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
Labels: PR state: review and merge, feature

#359 Fixes product edit page UI.
  apps/admin_app/assets/css/custom/custom.scss
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
Labels: PR state: review and merge, bug

#361 Fixes product show page order actions.
  apps/admin_app/lib/admin_app/order/order.ex
Labels: PR state: review and merge, bug

#357 Preserves filter on publish from edit page.
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/snitch_core/lib/core/tools/helpers/rummage.ex
  apps/snitch_core/test/tools/helpers/rummage_test.exs
Labels: PR state: review and merge, feature

#363 Product advanced section
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
Labels: PR state: review and merge

#365 Fixes rummage issue while adding a new product.
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/new.html.eex
  apps/snitch_core/lib/core/tools/helpers/rummage.ex
Labels: PR state: review and merge, bug

#348 Category slug support
  apps/admin_app/assets/js/views/taxonomy/taxonomy.js
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxonomy.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/taxon_edit_form.html.eex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
  apps/snitch_core/lib/core/tools/helpers/taxonomy.ex
  apps/snitch_core/priv/repo/migrations/20181130073311_add_category_slug.exs
  apps/snitch_core/test/domain/taxonomy/taxonomy_test.exs
  apps/snitch_core/test/support/factory/taxonomy.ex
  apps/snitch_core/test/tools/helpers/taxonomy_test.exs
Labels: PR state: review and merge

#360 Rename image name with unique key
  apps/admin_app/lib/admin_app_web/controllers/general_settings_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/product_brand_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/views/general_settings_view.ex
  apps/admin_app/lib/admin_app_web/views/product_brand_view.ex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/admin_app/lib/admin_app_web/views/template_api/taxonomy_view.ex
  apps/snitch_api/lib/snitch_api_web/views/product_brand_view.ex
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/config/test.exs
  apps/snitch_core/lib/core/data/model/general_configuration.ex
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/product_brand.ex
  apps/snitch_core/lib/core/data/schema/images/image.ex
  apps/snitch_core/lib/core/data/schema/product_brand.ex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
  apps/snitch_core/lib/core/tools/helpers/taxonomy.ex
  apps/snitch_core/lib/core/tools/mailer/email_templates/order_confirmation_email.html.eex
  apps/snitch_core/priv/repo/demo/demo_data/products.csv
  apps/snitch_core/priv/repo/demo/products.ex
  apps/snitch_core/priv/repo/migrations/20181212072305_add_url_to_image.exs
  apps/snitch_core/test/data/model/general_configuration_test.exs
  apps/snitch_core/test/data/model/image_test.exs
  apps/snitch_core/test/data/model/product_brand_test.exs
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/image.png
  apps/snitch_core/test/support/image_new.png
Labels: PR state: review and merge

#366 Display loading sign
  apps/admin_app/assets/js/views/product/edit.js
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/snitch_core/test/data/model/image_test.exs
Labels: PR state: review and merge

#367 Taxon (category) deletion
  apps/admin_app/assets/js/views/taxonomy/taxonomy.js
  apps/admin_app/lib/admin_app/application.ex
  apps/admin_app/lib/admin_app/honeydew_workers/category_worker.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/list.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxon.html.eex
  apps/admin_app/lib/admin_app_web/templates/taxonomy/taxonomy.html.eex
  apps/admin_app/lib/admin_app_web/templates/template_api/taxonomy/category_aggregate.html.eex
  apps/admin_app/lib/admin_app_web/views/template_api/taxonomy_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/domain/taxonomy/taxonomy.ex
  apps/snitch_core/lib/core/tools/multitenancy/repo.ex
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/domain/taxonomy/taxonomy_test.exs
Labels: PR state: review and merge

#370 Prevents redirection after adding a variant.
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
Labels: PR state: review and merge, feature

#369 Fixing the image url
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
Labels: PR state: review and merge

#372 Show 404 template
  apps/admin_app/assets/css/custom/custom.scss
  apps/admin_app/lib/admin_app_web.ex
  apps/admin_app/lib/admin_app_web/controllers/error_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/error/404.html.eex
  apps/admin_app/lib/admin_app_web/views/error_view.ex
  apps/admin_app/test/admin_app_web/views/error_view_test.exs
Labels: PR state: review and merge

#373 Sentry config fix for Dev env
  apps/admin_app/config/prod.exs
  apps/admin_app/mix.exs
  apps/snitch_api/config/prod.exs
  apps/snitch_api/mix.exs
  apps/snitch_core/config/prod.exs
  config/config.exs
Labels: PR state: review and merge

#371 Remove image resizing from image uploader
  apps/admin_app/lib/admin_app_web/controllers/template_api/taxonomy_controller.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
Labels: PR state: review and merge

#375 React integration
  apps/admin_app/assets/.babelrc
  apps/admin_app/assets/brunch-config.js
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/js/components/App.tsx
  apps/admin_app/assets/js/components/Hello.tsx
  apps/admin_app/assets/package.json
  apps/admin_app/assets/tsconfig.json
  apps/admin_app/assets/webpack.config.js
  apps/admin_app/assets/yarn.lock
  apps/admin_app/config/dev.exs
  apps/admin_app/lib/admin_app_web/auth_pipeline/authorize_plug.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/page_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/general_settings/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/page/index.html.eex
Labels: PR state: review and merge

#350 Advanced searching with elasticsearch 🔥🚀 - PHASE 1 (basic)
  .dockerignore
  .gitignore
  apps/snitch_api/lib/snitch_api/products_context/products_context.ex
  apps/snitch_api/lib/snitch_api_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_api/lib/snitch_api_web/views/elasticsearch/product_view.ex
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/.gitignore
  apps/snitch_core/config/config.exs
  apps/snitch_core/config/elasticsearch.exs
  apps/snitch_core/lib/core/application.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/product_review.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/tools/elasticsearch/README.md
  apps/snitch_core/lib/core/tools/elasticsearch/cluster.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product_search.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product_store.ex
  apps/snitch_core/lib/core/tools/multitenancy/repo.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/elasticsearch/products.json
  config/deploy.example/prod-start.sh
  config/docker/prod/Dockerfile
  env/example.env
  mix.lock
Labels: DONT MERGE, PR action: discuss, effort:medium (days), feature, hotlist: core-team, type: feature

#380 Stock location index page in phoenix temaplate
  apps/admin_app/assets/elm/.gitignore
  apps/admin_app/assets/elm/README.md
  apps/admin_app/assets/elm/elm-package.json
  apps/admin_app/assets/elm/public/favicon.ico
  apps/admin_app/assets/elm/public/index.html
  apps/admin_app/assets/elm/public/logo.svg
  apps/admin_app/assets/elm/public/manifest.json
  apps/admin_app/assets/elm/src/Main.elm
  apps/admin_app/assets/elm/src/Routing.elm
  apps/admin_app/assets/elm/src/StockLocations/List.elm
  apps/admin_app/assets/elm/src/StockLocations/ListItem.elm
  apps/admin_app/assets/elm/src/index.js
  apps/admin_app/assets/elm/src/main.scss
  apps/admin_app/assets/elm/src/registerServiceWorker.js
  apps/admin_app/assets/elm/tests/Tests.elm
  apps/admin_app/assets/elm/tests/elm-package.json
  apps/admin_app/assets/js/app.js
  apps/admin_app/assets/package.json
  apps/admin_app/assets/vendor/elm.js
  apps/admin_app/assets/yarn.lock
  apps/admin_app/lib/admin_app_web/templates/stock_location/index.html.eex
  apps/admin_app/package-lock.json
  config/docker/prod/Dockerfile
Labels: PR state: review and merge

#383 Fix css not building for admin app
  apps/admin_app/assets/css/app.scss
  apps/admin_app/assets/css/custom/custom.scss
  apps/admin_app/assets/css/custom/font-face.scss
  apps/admin_app/assets/css/sidebar.scss
  apps/admin_app/assets/fonts/avia1.eot
  apps/admin_app/assets/fonts/avia1.ttf
  apps/admin_app/assets/fonts/avia1.woff
  apps/admin_app/assets/fonts/avia1.woff2
  apps/admin_app/assets/package.json
  apps/admin_app/assets/postcss.config.js
  apps/admin_app/assets/webpack.config.js
  apps/admin_app/assets/yarn.lock
Labels: PR state: review and merge

#381 Package enum state
  apps/admin_app/lib/admin_app/order/order.ex
  apps/snitch_core/lib/core/data/schema/package.ex
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/lib/core/tools/ecto_enums/ecto_enums.ex
  apps/snitch_core/priv/repo/migrations/20181213125931_update_package_state_type.exs
  apps/snitch_core/test/data/schema/package_test.exs
Labels: PR state: review and merge, feature

#384 Default url
  apps/admin_app/lib/admin_app_web/controllers/general_settings_controller.ex
Labels: PR state: review and merge

#390 disable currency change
  apps/admin_app/lib/admin_app_web/templates/general_settings/_form.html.eex
Labels: PR state: review and merge

#388 Products index updated with generic filter query
  apps/snitch_api/lib/snitch_api_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_api/test/snitch_api_web/controllers/product_controller_test.exs
  apps/snitch_api/test/support/settings/products.json
  apps/snitch_core/lib/core/tools/elasticsearch/product.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product_search.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product_store.ex
  apps/snitch_core/priv/elasticsearch/products.json
  yarn.lock
Labels: PR state: review and merge

#391 Fix image file size issue after resize
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
Labels: PR state: review and merge

#389 Variant state change
  apps/admin_app/assets/js/views/product/edit.js
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
Labels: PR state: review and merge

#394 Dashboard datapoints consistency.
  apps/snitch_core/lib/core/data/model/order.ex
  apps/snitch_core/lib/core/data/model/payment/payment.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
Labels: feature

#386 Fetch states
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/stock_location/edit.js
  apps/admin_app/assets/js/views/stock_location/fetch_states.js
  apps/admin_app/assets/js/views/stock_location/new.js
  apps/admin_app/lib/admin_app_web/controllers/stock_location_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/views/data_helpers.ex
  apps/admin_app/lib/admin_app_web/views/layout_view.ex
  apps/snitch_core/lib/core/data/model/state.ex
  apps/snitch_core/test/data/model/state_test.exs
Labels: PR state: review and merge

#376 Product export
  apps/admin_app/lib/admin_app/application.ex
  apps/admin_app/lib/admin_app/honeydew_workers/export_data_worker.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/exporter/exporter.ex
  apps/admin_app/lib/admin_app_web/exporter/order.ex
  apps/admin_app/lib/admin_app_web/exporter/product.ex
  apps/admin_app/lib/admin_app_web/helpers.ex
  apps/admin_app/lib/admin_app_web/mailer/data_export_mail.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/order/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/data/model/order.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/support/factory/factory.ex
Labels: PR state: review and merge

#393 Product indexing: update index on product association updates
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/support/factory/factory.ex
Labels: PR state: review and merge

#396 Upload fix
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/test/data/model/product_test.exs
Labels: PR state: review and merge

#398 Feature/dev docker setup
  config/docker/dev/Dockerfile-dev
  config/docker/dev/docker-compose-dev.yml
  config/docker/dev/docker-dev-provision.sh
Labels: In Progress
