Repository aviacommerce/avia, pull requests merged in 2018-02, with the labels that each got.

#1 Basic address schema and migrations
  apps/core/lib/core/snitch/address.ex
  apps/core/priv/repo/migrations/20180212065208_create_address.exs
Labels: feature

#2 Added basic User model, with pwd encryption.
  apps/core/lib/core/snitch/user.ex
  apps/core/mix.exs
  apps/core/priv/repo/migrations/20180213064751_create_user.exs
  mix.lock
Labels: feature

#3 Use ex_money's Ecto type for price.
  apps/core/lib/core/snitch/variant.ex
  apps/core/priv/repo/migrations/20180213103123_add_money_with_currency_type_to_postgres.exs
  apps/core/priv/repo/migrations/20180213103411_variant_migrate_to_ex_money_amounts.exs
  apps/core/priv/repo/migrations/20180213180835_unique_index_variant_sku.exs
Labels: enhancement

#6 Structural changes and stock item
  apps/core/lib/core/snitch/data/model/inventory/stock_item.ex
  apps/core/lib/core/snitch/data/model/inventory/stock_location.ex
  apps/core/lib/core/snitch/data/model/model.ex
  apps/core/lib/core/snitch/data/schema/inventory/stock_item.ex
  apps/core/lib/core/snitch/data/schema/inventory/stock_location.ex
  apps/core/lib/core/snitch/data/schema/schema.ex
  apps/core/lib/core/snitch/variant.ex
  apps/core/lib/core/tools/helpers/query_helper/query_helper.ex
  apps/core/mix.exs
  apps/core/priv/repo/migrations/20180219065122_add_stock_locations_table.exs
  apps/core/priv/repo/migrations/20180219065809_add_stock_items_table.exs
  mix.lock
Labels: PR state: review and merge

#8 bug fixes and removed deleted field
  apps/core/lib/core/snitch/data/schema/inventory/stock_item.ex
  apps/core/lib/core/snitch/data/schema/inventory/stock_location.ex
  apps/core/lib/core/tools/helpers/query_helper/query_helper.ex
Labels: PR state: review and merge

#4 add state and country table
  apps/core/config/config.exs
  apps/core/lib/core/seed/country_state_seed.ex
  apps/core/lib/core/snitch/country.ex
  apps/core/lib/core/snitch/state.ex
  apps/core/mix.exs
  apps/core/priv/repo/migrations/20180212120541_create_snitch_countries.exs
  apps/core/priv/repo/migrations/20180212121350_create_snitch_states.exs
  apps/core/priv/repo/seeds.exs
  mix.lock
Labels: PR state: review and merge
