Repository aviacommerce/avia, pull requests merged in 2018-06, with the labels that each got.

#91 Product API endpoints and seeds
  apps/api/lib/api_web/controllers/order_controller.ex
  apps/api/lib/api_web/controllers/product_controller.ex
  apps/api/lib/api_web/router.ex
  apps/api/lib/api_web/views/order_view.ex
  apps/api/lib/api_web/views/product_view.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/data/schema/variant.ex
  apps/snitch_core/lib/core/data/schema/variant_image.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20180529171222_create_protyotype_hierarchy.exs
  apps/snitch_core/priv/repo/seed/product.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/seed_data/pets_shop/products.json
  mix.lock
Labels: WIP

#100 Computing shipments (packages) for an order
  apps/snitch_core/lib/core/data/model/package.ex
  apps/snitch_core/lib/core/data/model/stock/stock.ex
  apps/snitch_core/lib/core/data/model/stock/stock_location.ex
  apps/snitch_core/lib/core/data/schema/order.ex
  apps/snitch_core/lib/core/data/schema/package_item.ex
  apps/snitch_core/lib/core/data/schema/shipping_method.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
  apps/snitch_core/lib/core/domain/shipment.ex
  apps/snitch_core/lib/core/domain/shipment_engine.ex
  apps/snitch_core/lib/core/domain/shipping_method.ex
  apps/snitch_core/lib/core/domain/splitters/weight.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/test/data/schema/order_test.exs
  apps/snitch_core/test/data/schema/package_item_test.exs
  apps/snitch_core/test/domain/order/transitions_test.exs
  apps/snitch_core/test/domain/shipment_engine_test.exs
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/support/factory/shipping.ex
  mix.exs
  mix.lock
Labels: feature

#105 Seed Zone, ShippingMethod, ShippingCategory, etc
  .travis.yml
  apps/snitch_core/dots/demo.exs
  apps/snitch_core/dots/seed.exs
  apps/snitch_core/lib/core/data/model/zone/country_zone.ex
  apps/snitch_core/lib/core/data/model/zone/state_zone.ex
  apps/snitch_core/lib/core/data/model/zone/zone.ex
  apps/snitch_core/lib/core/data/schema/package.ex
  apps/snitch_core/lib/core/data/schema/package_item.ex
  apps/snitch_core/lib/core/domain/order/default_machine.ex
  apps/snitch_core/lib/core/domain/shipment.ex
  apps/snitch_core/lib/core/domain/shipment_engine.ex
  apps/snitch_core/lib/core/tools/helpers/order.ex
  apps/snitch_core/lib/core/tools/helpers/shipment.ex
  apps/snitch_core/lib/core/tools/helpers/stock.ex
  apps/snitch_core/lib/core/tools/helpers/zone.ex
  apps/snitch_core/priv/repo/migrations/20180526093804_order_belongs_to_address_and_stock_location_index.exs
  apps/snitch_core/priv/repo/seed/country_state.ex
  apps/snitch_core/priv/repo/seed/orders.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/priv/repo/seed/shipping.ex
  apps/snitch_core/priv/repo/seed/stocks.ex
  apps/snitch_core/priv/repo/seed/taxonomy.ex
  apps/snitch_core/priv/repo/seed/users.ex
  apps/snitch_core/test/data/model/package_item_test.exs
  apps/snitch_core/test/data/schema/package_item_test.exs
  apps/snitch_core/test/data/schema/package_test.exs
  apps/snitch_core/test/domain/shipment_engine_test.exs
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/domain/shipping_method_test.exs
  apps/snitch_core/test/domain/splitters/weight_test.exs
  apps/snitch_core/test/domain/zone_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/zone_case.ex
  mix.lock
Labels: enhancement

#108 Option type CRUD for admin
  apps/admin_app/lib/admin_app_web/controllers/option_type_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/templates/option_type/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/option_type/form.html.eex
  apps/admin_app/lib/admin_app_web/templates/option_type/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/option_type/new.html.eex
  apps/admin_app/lib/admin_app_web/views/option_type_view.ex
  apps/snitch_core/lib/core/data/model/option_type.ex
  apps/snitch_core/lib/core/data/schema/option_type.ex
  apps/snitch_core/lib/core/data/schema/template_option_value.ex
  apps/snitch_core/priv/repo/migrations/20180622101026_add_optiontype.exs
Labels: PR state: review and merge
