Repository aviacommerce/avia, pull requests merged in 2019-01, with the labels that each got.

#401 Currency fixes
  apps/admin_app/lib/admin_app_web/templates/general_settings/_form.html.eex
Labels: PR state: review and merge

#399 Elasticsearch category, range filter aggregations
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api_web/views/elasticsearch/product_view.ex
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_api/test/snitch_api_web/controllers/product_controller_test.exs
  apps/snitch_api/test/support/settings/products.json
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/product_review.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product_search.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product_store.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
  apps/snitch_core/priv/elasticsearch/products.json
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/factory/product.ex
Labels: PR state: review and merge

#387 Stock revamp
  apps/admin_app/assets/css/custom/custom.scss
  apps/admin_app/assets/js/views/product/edit.js
  apps/admin_app/lib/admin_app_web/controllers/api/stock_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/views/api/stock_view.ex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/stock/stock_item.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/data/schema/stock/stock_item.ex
  apps/snitch_core/lib/core/domain/package.ex
  apps/snitch_core/lib/core/domain/stock/inventory.ex
  apps/snitch_core/lib/core/tools/ecto_enums/ecto_enums.ex
  apps/snitch_core/priv/repo/migrations/20181227063242_add_inventory_tracking_field.exs
  apps/snitch_core/priv/repo/migrations/20181229094024_add_stock_item_low_level.exs
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/data/model/stock/stock_item_test.exs
  apps/snitch_core/test/domain/stock/inventory_test.exs
Labels: PR state: review and merge

#385 Refactor product controller function
  apps/snitch_core/test/data/model/product_test.exs
Labels: PR state: review and merge

#404 Arc upload fix
  .gitignore
  apps/admin_app/lib/admin_app/etsy_importer.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/general_configuration.ex
  apps/snitch_core/lib/core/data/schema/product_brand.ex
  apps/snitch_core/lib/core/data/schema/taxanomy/taxon.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
  apps/snitch_core/priv/repo/demo/products.ex
Labels: PR state: review and merge

#405 Image deletion fix
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/data/model/product.ex
Labels: PR state: review and merge

#410 Escape range filter selection from range filter aggregation filter
  apps/snitch_core/lib/core/tools/elasticsearch/product_search.ex
Labels: PR state: review and merge

#407 Upload from root
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/tools/helpers/image_uploader.ex
  apps/snitch_core/priv/repo/demo/products.ex
  apps/snitch_core/test/data/model/general_configuration_test.exs
  apps/snitch_core/test/data/model/product_brand_test.exs
  apps/snitch_core/test/tools/mailer/order_confirmation_email_test.exs
Labels: PR state: review and merge

#408 Handle stock reduction based on inventory tracking
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/domain/package.ex
  apps/snitch_core/lib/core/domain/stock/inventory.ex
  apps/snitch_core/test/domain/stock/inventory_test.exs
  apps/snitch_core/test/support/factory/stock.ex
Labels: PR state: review and merge

#411 Refactors and adds autocompletion with fuzzy search
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api/products_context/products_context.ex
  apps/snitch_api/lib/snitch_api_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api_web/router.ex
  apps/snitch_api/lib/snitch_api_web/views/elasticsearch/product/list_view.ex
  apps/snitch_api/lib/snitch_api_web/views/elasticsearch/product/suggest_view.ex
  apps/snitch_api/test/snitch_api_web/controllers/product_controller_test.exs
  apps/snitch_api/test/support/settings/products.json
  apps/snitch_core/config/config.exs
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/product_review.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/document.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/search.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/store.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/suggestor.ex
  apps/snitch_core/priv/elasticsearch/products.json
Labels: PR state: review and merge

#414 Auto completion api index document updates
  apps/snitch_api/lib/snitch_api_web/views/elasticsearch/product/suggest_view.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/document.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/suggestor.ex
Labels: PR state: review and merge

#416 Fix stock API failure on variant edit page
  apps/admin_app/assets/js/views/product/edit.js
Labels: PR state: review and merge

#415 Order number format modification
  apps/admin_app/lib/admin_app_web/templates/order/order_list_card.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/snitch_core/lib/core/data/model/user.ex
  apps/snitch_core/lib/core/data/schema/order.ex
  apps/snitch_core/priv/repo/demo/order.ex
  apps/snitch_core/test/data/model/user_test.exs
Labels: PR state: review and merge

#419 Caching Taxonomy and search responses as per the url
  apps/snitch_api/lib/snitch_api_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api_web/controllers/taxonomy_controller.ex
  apps/snitch_core/lib/core/application.ex
  apps/snitch_core/lib/core/tools/cache.ex
Labels: PR state: review and merge

#421 Role handling
  apps/admin_app/lib/admin_app_web/templates/role/index.html.eex
  apps/admin_app/lib/admin_app_web/views/role_view.ex
Labels: PR state: review and merge

#417 Variant deletion
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/snitch_core/lib/core/data/model/product.ex
Labels: PR state: review and merge

#420 User deletion fix
  apps/admin_app/lib/admin_app_web/controllers/user_controller.ex
  apps/snitch_core/lib/core/data/model/user.ex
  apps/snitch_core/lib/core/data/schema/user.ex
  apps/snitch_core/lib/core/tools/cache.ex
  apps/snitch_core/test/data/model/user_test.exs
Labels: PR state: review and merge

#422 handle order detail
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/snitch_core/lib/core/domain/order/order.ex
  apps/snitch_core/priv/repo/demo/order.ex
Labels: PR state: review and merge

#423 Test cases for country model
  apps/snitch_core/test/data/model/country_test.exs
Labels: PR state: review and merge

#425 Add upn number to uniquely identify products
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20190115093617_add_upn_field_to_products.exs
  apps/snitch_core/test/data/model/product_test.exs
Labels: PR state: review and merge

#429 test upi generation function
  apps/snitch_api/lib/snitch_api_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/priv/repo/migrations/20190117065101_add_upi_field_to_products.exs
  apps/snitch_core/test/data/model/product_test.exs
Labels: PR state: review and merge

#424 Test cases for Property Schema
  apps/snitch_core/test/data/schema/property_test.exs
Labels: PR state: review and merge

#427 Test cases for Property Model
  apps/snitch_core/test/data/model/property_test.exs
Labels: PR state: review and merge

#431 fix pattern match for get property response
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/snitch_core/test/data/schema/property_test.exs
Labels: PR state: review and merge

#432 Response tuple fix
  apps/admin_app/lib/admin_app/order/order.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/product_brand_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/promotion_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/prototype_controller.ex
  apps/snitch_core/lib/core/data/model/tax_category.ex
  apps/snitch_core/lib/core/data/model/tax_rate.ex
  apps/snitch_core/test/data/model/tax_category_test.exs
  apps/snitch_core/test/data/model/tax_rate_test.exs
Labels: PR state: review and merge

#441 update product state
  apps/snitch_core/priv/repo/demo/products.ex
Labels: PR state: review and merge

#443 Test cases for Package_Item(Model)
  apps/snitch_core/test/data/model/package_item_test.exs
Labels: PR state: review and merge

#442 Handle product edit
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
Labels: PR state: review and merge

#444 restricting deletion of option types
  apps/admin_app/lib/admin_app_web/controllers/option_type_controller.ex
  apps/snitch_core/lib/core/data/model/option_type.ex
  apps/snitch_core/test/data/model/option_type_test.exs
Labels: PR state: review and merge

#440 Add Tax Configuration and Tax Class
  apps/admin_app/lib/admin_app_web/controllers/tax_category_controller.ex
  apps/admin_app/lib/admin_app_web/templates/tax_category/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax_category/new.html.eex
  apps/admin_app/lib/admin_app_web/views/tax_category_view.ex
  apps/snitch_core/lib/core/data/model/tax/tax_class.ex
  apps/snitch_core/lib/core/data/model/tax/tax_configuration.ex
  apps/snitch_core/lib/core/data/model/tax_category.ex
  apps/snitch_core/lib/core/data/model/tax_rate.ex
  apps/snitch_core/lib/core/data/schema/tax/tax_class.ex
  apps/snitch_core/lib/core/data/schema/tax/tax_config.ex
  apps/snitch_core/lib/core/data/schema/tax_category.ex
  apps/snitch_core/lib/core/data/schema/tax_rate.ex
  apps/snitch_core/lib/core/tools/ecto_enums/ecto_enums.ex
  apps/snitch_core/priv/repo/migrations/20190122083704_add_tax_class_and_config_table.exs
  apps/snitch_core/priv/repo/seed/tax.ex
  apps/snitch_core/test/data/model/tax/tax_class_test.exs
  apps/snitch_core/test/data/model/tax/tax_config_test.exs
  apps/snitch_core/test/data/model/tax_category_test.exs
  apps/snitch_core/test/data/model/tax_rate_test.exs
  apps/snitch_core/test/data/schema/tax/tax_class_test.exs
  apps/snitch_core/test/data/schema/tax/tax_config_test.exs
  apps/snitch_core/test/data/schema/tax_category_test.exs
  apps/snitch_core/test/data/schema/tax_rate_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/factory/tax.ex
Labels: PR state: review and merge, feature

#436 test upi generation
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/taxonomy_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/tools/generate_nanoid.ex
  apps/snitch_core/mix.exs
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/support/nanoid_mock.ex
  mix.lock
Labels: PR state: review and merge

#445 Modify general setting validations
  apps/admin_app/lib/admin_app_web/templates/general_settings/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/general_settings/index.html.eex
  apps/snitch_core/lib/core/data/schema/general_configuration.ex
  apps/snitch_core/priv/repo/migrations/20190123130059_remove_hosted_payment_url_from_general_config.exs
  apps/snitch_core/test/data/model/general_configuration_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/tools/mailer/order_confirmation_email_test.exs
Labels: PR state: review and merge

#448 Add UI for TaxClass and Tax Configuration.
  apps/admin_app/assets/js/views/loader.js
  apps/admin_app/assets/js/views/tax/tax_class_index.js
  apps/admin_app/assets/js/views/tax/tax_config_index.js
  apps/admin_app/lib/admin_app_web/controllers/tax/tax_class_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/tax/tax_config_controller.ex
  apps/admin_app/lib/admin_app_web/endpoint.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/main.html.eex
  apps/admin_app/lib/admin_app_web/templates/layout/sidebar.html.eex
  apps/admin_app/lib/admin_app_web/templates/role/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_class/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_class/_tax_class.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_class/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_class/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_class/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_config/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_config/tax_layout.html.eex
  apps/admin_app/lib/admin_app_web/views/data_helpers.ex
  apps/admin_app/lib/admin_app_web/views/layout_view.ex
  apps/admin_app/lib/admin_app_web/views/tax/tax_class_view.ex
  apps/admin_app/lib/admin_app_web/views/tax/tax_config_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/model/tax/tax_class.ex
  apps/snitch_core/lib/core/data/model/tax/tax_configuration.ex
  apps/snitch_core/test/data/model/package_item_test.exs
  apps/snitch_core/test/data/model/tax/tax_class_test.exs
  apps/snitch_core/test/data/model/tax/tax_config_test.exs
Labels: PR state: review and merge, feature

#447 PackageItem schema test
  apps/snitch_core/test/data/schema/package_item_test.exs
Labels: PR state: review and merge

#450 Test for Product_property (Model)
  apps/snitch_core/test/data/model/product_property_test.exs
Labels: waiting for requested changes

#437 Fetch products with active variants
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/snitch_api/lib/snitch_api/products_context/products_context.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/tools/mailer/email_templates/order_confirmation_email.html.eex
Labels: PR state: review and merge

#451 User deletion
  apps/snitch_core/lib/core/data/model/user.ex
  apps/snitch_core/lib/core/data/schema/user.ex
  apps/snitch_core/lib/core/domain/account/account.ex
  apps/snitch_core/lib/core/tools/ecto_enums/ecto_enums.ex
  apps/snitch_core/priv/repo/migrations/20190124100852_add_user_state_field.exs
  apps/snitch_core/priv/repo/migrations/20190128081011_update_user_unique_index.exs
  apps/snitch_core/priv/repo/seed/users.ex
  apps/snitch_core/test/data/model/user_test.exs
  apps/snitch_core/test/data/schema/user_test.exs
Labels: PR state: review and merge

#457 search products by name
  apps/admin_app/assets/js/socket.js
  apps/admin_app/assets/js/views/product/index.js
  apps/admin_app/lib/admin_app/product/search.ex
  apps/admin_app/lib/admin_app_web/channels/product_channel.ex
  apps/admin_app/lib/admin_app_web/channels/user_socket.ex
  apps/admin_app/lib/admin_app_web/current_user.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/layout/app.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
Labels: PR state: review and merge

#456 Add UI for Tax Zone and Tax Rates
  apps/admin_app/lib/admin_app_web/controllers/tax/tax_rate_controller.ex
  apps/admin_app/lib/admin_app_web/controllers/tax/tax_zone_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_config/tax_layout.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_rate/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_rate/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_rate/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_rate/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_zone/_form.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_zone/edit.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_zone/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_zone/new.html.eex
  apps/admin_app/lib/admin_app_web/templates/tax/tax_zone/tax_zone_layout.html.eex
  apps/admin_app/lib/admin_app_web/views/data_helpers.ex
  apps/admin_app/lib/admin_app_web/views/tax/tax_rate_view.ex
  apps/admin_app/lib/admin_app_web/views/tax/tax_zone_view.ex
  apps/snitch_core/lib/core/data/model/tax/tax_rate.ex
  apps/snitch_core/lib/core/data/model/tax/tax_zone.ex
  apps/snitch_core/lib/core/data/model/zone/zone.ex
  apps/snitch_core/lib/core/data/schema/tax/tax_rate_class_value.ex
  apps/snitch_core/lib/core/data/schema/tax/tax_zone.ex
  apps/snitch_core/priv/repo/seed/seeds.exs
  apps/snitch_core/test/data/model/tax/tax_rate_test.exs
  apps/snitch_core/test/data/model/tax/tax_zone_test.exs
Labels: PR state: review and merge, feature

#454 Test for CountryZoneMember and StateZoneMember (model/schema)
  apps/snitch_core/test/data/model/zone/country_zone_test.exs
  apps/snitch_core/test/data/model/zone/state_zone_test.exs
  apps/snitch_core/test/data/schema/zone/country_zone_member_test.exs
  apps/snitch_core/test/data/schema/zone/state_zone_member_test.exs
Labels: PR state: WIP
