Repository aviacommerce/avia, pull requests merged in 2019-02, with the labels that each got.

#461 optimisation for product page
  apps/admin_app/lib/admin_app/product/search.ex
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/product/_product_card.html.eex
  apps/admin_app/lib/admin_app_web/templates/product/index.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
Labels: PR state: review and merge

#463 Add api scope to promotions API's
  apps/admin_app/lib/admin_app_web/router.ex
Labels: PR state: review and merge

#464 search orders
  apps/admin_app/assets/js/views/order/index.js
  apps/admin_app/lib/admin_app/order/order.ex
  apps/admin_app/lib/admin_app/order/search.ex
  apps/admin_app/lib/admin_app_web/channels/order_channel.ex
  apps/admin_app/lib/admin_app_web/channels/product_channel.ex
  apps/admin_app/lib/admin_app_web/channels/user_socket.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/templates/order/index.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/snitch_core/lib/core/data/model/general_configuration.ex
  apps/snitch_core/priv/repo/migrations/20190205074406_add_order_index.exs
Labels: PR state: review and merge

#465 Add tax domain
  apps/admin_app/lib/admin_app_web/controllers/product_controller.ex
  apps/admin_app/lib/admin_app_web/templates/product/form.html.eex
  apps/admin_app/lib/admin_app_web/views/product_view.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/package_item.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/domain/calculator/default_tax_calculator.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
  apps/snitch_core/lib/core/domain/package.ex
  apps/snitch_core/lib/core/domain/package_item.ex
  apps/snitch_core/lib/core/domain/shipment.ex
  apps/snitch_core/lib/core/domain/tax.ex
  apps/snitch_core/priv/repo/demo/products.ex
  apps/snitch_core/priv/repo/migrations/20190131112645_modify_prod_pack_item_for_tax.exs
  apps/snitch_core/test/data/model/option_type_test.exs
  apps/snitch_core/test/data/model/package_item_test.exs
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/data/model/tax/tax_zone_test.exs
  apps/snitch_core/test/data/schema/package_item_test.exs
  apps/snitch_core/test/data/schema/product_test.exs
  apps/snitch_core/test/data/schema/tax/tax_config_test.exs
  apps/snitch_core/test/domain/calculator/default_calculator_test.exs
  apps/snitch_core/test/domain/calculator/flat_percent_calculator_test.exs
  apps/snitch_core/test/domain/order/transitions_test.exs
  apps/snitch_core/test/domain/package_test.exs
  apps/snitch_core/test/domain/shipment_test.exs
  apps/snitch_core/test/domain/tax_test.exs
  apps/snitch_core/test/support/factory/factory.ex
  apps/snitch_core/test/support/factory/product.ex
  apps/snitch_core/test/support/factory/shipping.ex
  apps/snitch_core/test/support/factory/tax.ex
Labels: PR state: review and merge, feature

#468 Async email
  apps/snitch_core/lib/core/application.ex
  apps/snitch_core/lib/core/data/model/images.ex
  apps/snitch_core/lib/core/domain/order/transitions.ex
  apps/snitch_core/lib/core/tools/mailer/mail_worker.ex
  apps/snitch_core/priv/repo/migrations/20190206091901_update_general_config_seo_title.exs
Labels: PR state: review and merge

#473 Pagination for orders
  apps/admin_app/assets/js/views/order/index.js
  apps/admin_app/lib/admin_app/order/order.ex
  apps/admin_app/lib/admin_app/order/search.ex
  apps/admin_app/lib/admin_app/pagination.ex
  apps/admin_app/lib/admin_app_web.ex
  apps/admin_app/lib/admin_app_web/channels/order_channel.ex
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
  apps/admin_app/lib/admin_app_web/router.ex
  apps/admin_app/lib/admin_app_web/templates/general_settings/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/order/order_listing.html.eex
  apps/admin_app/lib/admin_app_web/views/order_view.ex
  apps/admin_app/lib/admin_app_web/views/pagination_helper.ex
  apps/snitch_core/lib/core/domain/stock/quantifier.ex
  apps/snitch_core/test/data/model/general_configuration_test.exs
Labels: PR state: review and merge

#474 function rebinding fixes
  apps/admin_app/assets/js/views/order/index.js
  apps/admin_app/lib/admin_app_web/controllers/order_controller.ex
Labels: PR state: review and merge

#460 Test Shipping related models and schema
  apps/snitch_core/lib/core/data/model/shipping_category.ex
  apps/snitch_core/lib/core/data/model/shipping_rule.ex
  apps/snitch_core/lib/core/data/schema/shipping_rules/shipping_rule_identifier.ex
  apps/snitch_core/test/data/model/shipping_category_test.exs
  apps/snitch_core/test/data/model/shipping_method_test.exs
  apps/snitch_core/test/data/model/shipping_rule_test.exs
  apps/snitch_core/test/data/schema/shipping_rules/shipping_rule_identifier_test.exs
Labels: PR state: review and merge, Testing

#469 Add default zone and tax zone
  apps/admin_app/lib/admin_app_web/templates/tax/tax_zone/index.html.eex
  apps/admin_app/lib/admin_app_web/templates/zone/index.html.eex
  apps/snitch_core/lib/core/data/model/tax/tax_zone.ex
  apps/snitch_core/lib/core/data/model/zone/zone.ex
  apps/snitch_core/lib/core/data/schema/tax/tax_zone.ex
  apps/snitch_core/lib/core/data/schema/zone/zone.ex
  apps/snitch_core/lib/core/domain/tax.ex
  apps/snitch_core/priv/repo/migrations/20190206050019_add_default_field_zone.exs
  apps/snitch_core/priv/repo/seed/shipping.ex
  apps/snitch_core/priv/repo/seed/tax.ex
  apps/snitch_core/test/data/model/tax/tax_zone_test.exs
  apps/snitch_core/test/data/schema/tax/tax_zone_test.exs
  apps/snitch_core/test/domain/tax_test.exs
  apps/snitch_core/test/support/factory/tax.ex
Labels: PR state: review and merge, enhancement

#471 Tests for review_related model and schema
  apps/snitch_core/test/data/model/product_review_test.exs
  apps/snitch_core/test/data/model/review_test.exs
  apps/snitch_core/test/data/schema/review/product_review_test.exs
  apps/snitch_core/test/data/schema/review/review_test.exs
  apps/snitch_core/test/support/factory/rating.ex
Labels: PR state: review and merge, Testing

#477 Handle error on duplicating product name
  apps/admin_app/lib/admin_app/product/search.ex
  apps/snitch_core/lib/core/data/model/product.ex
  apps/snitch_core/lib/core/data/schema/product.ex
  apps/snitch_core/lib/core/tools/elasticsearch/product/store.ex
  apps/snitch_core/priv/repo/migrations/20190219100843_alter_products_table.exs
  apps/snitch_core/test/data/model/product_test.exs
  apps/snitch_core/test/data/schema/product_test.exs
Labels: bug

#480 MultiResult Error
  apps/snitch_api/lib/snitch_api/products_context/products_context.ex
Labels: PR state: review and merge, bug
